### ISSUE TITLE
'v-for' directives require 'v-bind:key' directives.

### ISSUE THREAD

**Issue by ideal123** [octref/vetur#261] opened 2017-06-23 03:51 UTC
- Platform:  win10
- Vetur version: 0.8.3
- VSCode version: 1.13.1

'v-for' directives require 'v-bind:key' directives when I use `<li class="item-right" v-for="n in 19">{{ n }}</li>.`

**Comment by ideal123** [comment] 2017-06-23 04:22
![_20170623122147](https://user-images.githubusercontent.com/8275243/27466601-8cefea30-580e-11e7-96a8-8496ee443234.png)

**Comment by emrekaranfil** [comment] 2017-06-23 04:47
I have with this problem. I did not understand why.

![capture1](https://user-images.githubusercontent.com/9162729/27467032-a500ee0c-57e7-11e7-9816-24f49fd4012b.JPG)
![2017-06-23 07_42_32-posted vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899bec30e9d](https://user-images.githubusercontent.com/9162729/27467036-ac26aac8-57e7-11e7-9e83-07119100b23b.jpg)
![2017-06-23 07_44_40- mainfeed vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899bec30](https://user-images.githubusercontent.com/9162729/27467061-e1047a36-57e7-11e7-9d4b-5da1a1fa769b.jpg)
![2017-06-23 07_46_25-authentication vue - havacidan-com-development-95cc0e97636358ee5c366238802bd899b](https://user-images.githubusercontent.com/9162729/27467096-2a2eb3fc-57e8-11e7-9574-4347a9864255.jpg)

**Comment by topul** [comment] 2017-06-23 05:39
In 2.2.0+, when using v-for with a component, a key is now required.

**Comment by topul** [comment] 2017-06-23 05:43
but 

> <template> cannot be keyed. Place the key on real elements instead.

This is still a bug

**Comment by topul** [comment] 2017-06-23 05:44
but 

# <template> cannot be keyed. Place the key on real elements instead.

This is still a bug

**Comment by topul** [comment] 2017-06-23 05:44
but 

> "<template> cannot be keyed. Place the key on real elements instead."

This is still a bug

**Comment by topul** [comment] 2017-06-23 05:45
but, this is still a bug

>  \<template\> cannot be keyed. Place the key on real elements instead.

**Comment by topul** [comment] 2017-06-23 05:48
but, this is still a bug

![_20170623134735](https://user-images.githubusercontent.com/8213229/27468138-a1c9a1f6-581a-11e7-9e83-5ae1326972c6.png)
![_20170623134758](https://user-images.githubusercontent.com/8213229/27468139-a1de847c-581a-11e7-819f-a924d6f82424.png)

**Comment by HerringtonDarkholme** [comment] 2017-06-23 05:55
@ideal123  This is intended ESLint feature.  You can turn off eslint check in future release.  See https://github.com/octref/vetur/pull/235#issuecomment-310528300

@emrekaranfil  Would you mind provide an example repo for this problem? It seems eslint is reporting at wrong location.

@topul  This is a valid bug! Ping @mysticatea, any idea?

**Comment by ideal123** [comment] 2017-06-23 06:50
@topul I use v-for with a html element, and a key is unnecessary

@HerringtonDarkholme  I disabled ESlint Plugin, but there is the same error.

**Comment by HerringtonDarkholme** [comment] 2017-06-23 06:55
@ideal123 ESLint support is builtin with vetur. Please peruse #235. Closing vetur's builtin eslint has already been scheduled.

For the bug in this issue, it has been extracted in #263 and fixed in #264. 

So close this issue now.

**Closed by HerringtonDarkholme** 2017-06-23 06:55 UTC
Labels: upstream

**Comment by Villae** [comment] 2017-07-07 10:02
I think that this is still issue with vetur version 0.8.6.
"In 2.2.0+, when using v-for **with a component**, a key is now required."

-> key is required **with a component**, but it should not be required with a html element like <li> (in ideal123's case) or <option> (in my case), etc.

**Comment by octref** [comment] 2017-07-07 10:12
I'll publish a new version soon!

**Comment by SmileyChris** [comment] 2017-07-24 11:10
I see v0.0.10 was released 12 days ago, but I'm not sure it contained a fix for this. If not, perhaps this issue should be reopened since it seems it is still a problem currently.

**Comment by octref** [comment] 2017-07-24 18:14
Forgot to update dependency for eslint...
Try 0.9.3 or upgrade local `eslint-plugin-vue@beta`.

**Comment by grugknuckle** [comment] 2017-08-02 13:33
I am still getting a form of this error. I have Vetur 0.9.3 installed as plug-in to VS Code. I have globally installed `eslint-plugin-vue@beta` and `eslint4.3.0`. But in my .vue file I have
 
![vetur_err](https://user-images.githubusercontent.com/15350004/28875901-4655a580-7765-11e7-97ce-b6fd39690941.png)

`[vue-language-server] Elements in iteration expect to have 'v-bind:key' directives.`

I should point out that VS Code gives me complaint when I copy&paste the basic usage code directly frrom the Vue.js [documentation.](https://vuejs.org/v2/guide/list.html#Basic-Usage).

**Comment by octref** [comment] 2017-08-02 14:30
The behavior only depends on `eslint-plugin-vue@beta` installed locally.

**Comment by HerringtonDarkholme** [comment] 2017-08-02 14:51
@grugknuckle This is intended feature from eslint-vue. 

https://github.com/vuejs/eslint-plugin-vue/pull/45/files#diff-b013f11a89eed99206147599342d1bbdR51

You can turn off vetur's lint and use vscode-eslint to customize your rules.

**Comment by grugknuckle** [comment] 2017-08-02 17:20
Ok. Thank you. I can see that this is working as intended in the sense that there is a unit test for it. 

Can anyone explain *why* this test is here? What is the purpose of throwing an invalid warning on code which is identical to what it suggested in the vue.js documentation for the v-for directive? See for example, the basic usage code here

https://vuejs.org/v2/guide/list.html#Basic-Usage

I'm just curious as to what code pattern this is supposed to prevent. So that I can do it right.

**Comment by mysticatea** [comment] 2017-08-02 18:17
There are 2 rules about v-for and v-bind:key. One is `vue/no-invalid-v-for` in "Possible errors" category. This reports custom components which don't have v-bind:key. One is `vue/require-v-for-keys` in "Best practice" category. This reports normal elements which don't have v-bind:key.

Vue core team has recommended to use v-bind:key at all, but it's not errors on non custom components which don't have v-bind:key, so you can disable `vue/require-v-for-keys`.

**Comment by grugknuckle** [comment] 2017-08-02 18:28
Perfect! Thank you.

**Comment by think2cat** [comment] 2017-08-25 03:46
maybe vscode only,  webstorm have not report this error

**Comment by hryamzik** [comment] 2017-08-30 11:21
> The behavior only depends on eslint-plugin-vue@beta installed locally.

@octref so does it come as a dependency? Does it have to be updated in some specific way?

**Comment by RobinHerbots** [comment] 2017-09-04 09:02
@grugknuckle , 

add v-bind:key="the key property" on your li item

**Comment by aprilandjan** [comment] 2017-09-08 08:11
Suuuper annoying! Everytime I opened the vue files developed by other colleagues, the red lines 
blinded my eyes!

**Comment by HerringtonDarkholme** [comment] 2017-09-08 08:16
I don't want to be rude. But I hope someone can read the doc before complaining about their visual handicap. 

https://github.com/vuejs/vetur/blob/master/docs/linting-error.md#linting

Again, VueJS recommend to add key to every element and component. Considering to add an eslint step to your project and teaching your teammate is a good choice.

**Comment by aprilandjan** [comment] 2017-09-08 08:34
@HerringtonDarkholme , I agree with what you said, but for an old vue project that's not easy to do.

**Comment by HerringtonDarkholme** [comment] 2017-09-08 08:58
Thanks for understanding.

My point is current default setting is legitimate. As a tool for everyone, default setting should reflect best practice.

Please **configure your editor for your project**. Thanks.

**Comment by samayo** [comment] 2017-09-25 08:36
Why is binding a key necessary? This error shouldn't appear imho, since `v-for` works without binding a key

**Comment by HerringtonDarkholme** [comment] 2017-09-25 08:41
> It is recommended to provide a key with v-for whenever possible

https://vuejs.org/v2/guide/list.html#key

**Comment by Matt-Dionis** [comment] 2017-09-28 20:02
I've tried to add a `:key` to my template which `v-for` sits on but that causes the following error:
`<template> cannot be keyed. Place the key on real elements instead.`
Guess in this case it makes sense to just ignore the Vetur triggered warning, but would be nice if this warning was disabled for `template` elements.

**Comment by HerringtonDarkholme** [comment] 2017-09-29 00:34
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-template-key.md

**Comment by lqh21** [comment] 2017-10-12 09:27
*In 2.2.0+, when using v-for with a component, a key is now required.*
from (vue.org)[https://vuejs.org/v2/guide/list.html#key]

**Comment by lqh21** [comment] 2017-10-12 09:27
In 2.2.0+, when using v-for with a component, a key is now required.
from [vue.org](https://vuejs.org/v2/guide/list.html#key)

**Comment by lukeramsden** [comment] 2017-10-17 12:56
@Yawytya Yes, but the error still appears when you aren't using a component, but a HTML component.

**Comment by samayo** [comment] 2017-10-17 13:14
If your component or element has no keys, you can do this: 

```html
<p v-for='(person, index) in people' :key='index'> </p>
```

**Comment by ADTC** [comment] 2017-11-26 00:52
> you can disable `vue/require-v-for-keys`

Where? 😕

**Comment by MaxMcKinney** [comment] 2018-01-12 21:10
@samayo Where can I learn more about this syntax of including index in the parens with the current iteration item title? I haven't seen that before.

**Comment by nickforddesign** [comment] 2018-01-12 21:19
@MaxMcKinney https://vuejs.org/v2/guide/list.html second code example

**Comment by lmj0011** [comment] 2018-01-20 05:51
https://github.com/vuejs/vetur/issues/261#issuecomment-337227336

documentation: https://vuejs.org/v2/guide/list.html#v-for-with-an-Object

looks like you have use that syntax even if you're iterating through an **Array of Objects**

**Comment by danawesome** [comment] 2018-02-07 23:21
@samayo Thank you very much!!

**Comment by deveplon** [comment] 2018-03-05 00:23
This error is because Vue recommends use v-bind:key="". If you don't want a see the error just put the key there. See more here:

https://vuejs.org/v2/guide/list.html#key

**Comment by bagermen** [comment] 2018-03-08 08:25
Why I see the error again and again?? Isn't it easier to resolve the core reason. It's obvious that validation rules are not right

**Comment by nickforddesign** [comment] 2018-03-08 14:37
@bagermen when you use a linter with a config, it's going to show you errors if you don't follow the rules of the config. if you don't like the rules, you change the rules.

you can either include the `key` attribute, or add `'vue/require-v-for-keys': 0` to the rules of your eslintrc file.

**Comment by octref** [comment] 2018-03-08 19:12
@chrisvfritz
Do you think the documentation could be improved per @grugknuckle's suggestion?

**Comment by chrisvfritz** [comment] 2018-03-10 09:14
Yes it can. 🙂 Adding it to the list.

**Comment by foo614** [comment] 2018-04-04 16:36
simple to add  <div v-for="item in items" **:key="item.id"**>

In 2.2.0+, when using v-for with a component, a key is now required.

**Comment by antcosic** [comment] 2018-04-05 12:53
Even better solution would be:
<div v-for="(item, index) in items" :key="index">
so you don't need any unique property in your object.

**Comment by marsostar** [comment] 2018-04-05 12:55
@antcosic Saved our project , best solution ever!

**Comment by samayo** [comment] 2018-04-05 13:31
@antcosic how is that different from what I said?

**Comment by grugknuckle** [comment] 2018-04-05 13:33
@samayo Because with @marsostar 's solution, you don't need to pass the id data back and forth. The index is generated by vue's renderer only when it's needed.

<div v-for="(item, index) in items" :key="index">

compare to your solution where the item.id data has to be passed around.

<div v-for="item in items" :key="item.id">

**Comment by sudhir600** [comment] 2018-05-07 12:45
@antcosic solution work but it unnecessary. how to fix this globally

**Comment by sudhir600** [comment] 2018-05-08 07:26
@HerringtonDarkholmeI I gone through the link and added code snippet in package.json. But still its throwing error if i am not adding :key 

In html- 
`<div class="iteamBox" v-for="n in 10"> ...</div>`

And in package.json
```
"extends": [
    "eslint:recommended",
    "plugin:vue/recommended"
  ],
  "rules": {
    "vue/html-self-closing": "off"
  }
```


and Here is the error - 
![image](https://user-images.githubusercontent.com/4952560/39743524-c4310712-52be-11e8-8eb3-6317ee8dc0ed.png)


**Note**  Its only worked if use like this  -  `v-for="(item, index) in 10" :key="index"`

**Comment by HerringtonDarkholme** [comment] 2018-05-08 07:35
Change the specific line 

`"vue/html-self-closing": "off"` 

to 

`"vue/require-v-for-keys": "off"`.

**Comment by Binaryify** [comment] 2018-05-08 08:06
`"vetur.validation.template": false` is work for me

**Comment by sudhir600** [comment] 2018-05-08 09:13
@HerringtonDarkholme  @Binaryify 
both soltion is not working.

I have created a [repo](https://github.com/sudhir600/nuxt-v-for-key-false.git). 
may you please solve in that repo?

https://github.com/sudhir600/nuxt-v-for-key-false.git

**Comment by HerringtonDarkholme** [comment] 2018-05-08 09:17
> Set ESLint rules in .eslintrc.

https://vuejs.github.io/vetur/linting-error.html#linting-for-template

Not in package.json. https://github.com/sudhir600/nuxt-v-for-key-false/blob/master/package.json#L25-L32


Please use [our forum](https://forum.vuejs.org), [chat room](https://chat.vuejs.org) or StackOverflow to ask usage question since issue tracker is exclusively for bug reports and feature requests. Thanks.

**Comment by Binaryify** [comment] 2018-05-08 10:43
@sudhir600 I set that on vscode settings.json file 
![image](https://user-images.githubusercontent.com/12221718/39752949-ac16df36-52ef-11e8-9848-1cae16a9c21c.png)

**Comment by sudhir600** [comment] 2018-05-08 10:49
@Binaryify, where i will find settings.json file. i didn't see my directory.  And if i have to create new file then where i have to mention (like in nuxt.config or middleware) ?

**Comment by HerringtonDarkholme** [comment] 2018-05-08 10:51
**Please use [our forum](https://forum.vuejs.org), [chat room](https://chat.vuejs.org) or StackOverflow to ask usage question since issue tracker is exclusively for bug reports and feature requests. Thanks.**

GitHub issue will notify all people in this thread so please use forum/stackoverflow for questions. Thanks.

**Comment by sudhir600** [comment] 2018-05-08 11:13
ok @HerringtonDarkholme 

thanks

**Comment by iwootten** [comment] 2018-05-17 10:37
I found that the only solution that worked for me here was to set:

    "vue/require-v-for-key": "off"

In my .eslintrc.js - note "key" vs "keys".

**Comment by Hujjat** [comment] 2018-05-19 12:12
For me this worked. just add the ``` :key="item.id" ``` to your loop
```
<div v-for="item in items" :key="item.id">
  <!-- content -->
</div>
```

**Comment by tvviem** [comment] 2018-06-20 03:05
Basic: 
`<template>
  <ul>
      <li v-for="(item, index) in ninjas" :key="index"> {{ item }} </li>
  </ul>
</template>`

**Comment by tvviem** [comment] 2018-06-20 03:05
Maybe work!
```
<template>
  <ul>
      <li v-for="(item, index) in ninjas" :key="index"> {{ item }} </li>
  </ul>
</template>
```

**Comment by samarth-math** [comment] 2018-07-15 19:54
`It is recommended to provide a key with v-for whenever possible, unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains.`

That the above statement exists in the docs clearly implies this is a bug and NOT a valid error. At best this can be a warning, the fact that this is an error means it's a bug that needs to be fixed.

**Comment by chrisvfritz** [comment] 2018-07-15 21:32
I just want clarify again that **this is _not_ a bug in Vetur**. They're just applying the `essentials` category of the official [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) by default. We've chosen to include a rule called `require-v-for-key` in that category, which warns about all instances of missing keys, because there's a sizable list of scenarios where a missing key _can_ cause an error and it's easier to quickly add a `key` every time you use `v-for` than try to remember when it might be necessary.

We're [considering updating this rule](https://github.com/vuejs/eslint-plugin-vue/issues/522) to warn specifically about those scenarios and provide more specific warnings about why a `key` is necessary in those cases. In the meantime though, trust me that the rule in its current form helps people avoid _many_ difficult-to-debug problems in exchange for a relatively minor inconvenience.

**Comment by xiaomizhou66** [comment] 2018-07-30 07:56
<li v-for="item in items" :key="item.xxx">
xxx是对象数组中的属性

**Comment by octref** [comment] 2018-08-01 17:16
@chrisvfritz Awesome, will track it.

**Comment by SaphiLC** [comment] 2018-09-07 18:53
i dont understand why this is REQUIRED when the docs say its recommended, even more
```
<div :id="'tag-' + index" class="uk-width-auto" v-for="tag in tags" :key="index">
```
results in an id of "tag-undefined" while
```
<div :id="'tag-' + index" class="uk-width-auto" v-for="(tag, index) in tags">
```
results in "tag-0" etc but with error in the IDE
```
and adding both
```
<div :id="'tag-' + index" class="uk-width-auto" v-for="(tag, index) in tags" :key="index">
```
feels stupid and not necesary since its defining the key twice (?)

**Comment by nickforddesign** [comment] 2018-09-07 19:06
@SaphiLC You're not _defining_ the key twice, you're choosing to use it twice. Why not skip the ID altogether? 99% of the time, unless you are dealing with `<label>` for inputs, there is a better solution than using ids.

**Comment by tvviem** [comment] 2018-09-08 01:41
please view more at:
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/require-v-for-key.md

**Comment by DamengRandom** [comment] 2018-10-06 07:45
please check official doc (v-for) part, solution was add :key="item.id".

**Comment by mbonubasil** [comment] 2018-10-15 13:20
@Anzimanpkp's solution worked like a magic for me.
Just add `:key="somekey"` to you code.

`<li v-for='hero in heros' v-on:click='hero.show = !hero.show' :key="hero">`

Thanks @Anzimanpkp

**Comment by tvquangdn** [comment] 2018-10-24 08:58
Code like this: <div v-for="x in list" :key="x.id"></div>

**Comment by tvquangdn** [comment] 2018-10-24 08:59
Code like this: `<div v-for="x in list" :key="x.id"></div>`
https://github.com/mysticatea/eslint-plugin-vue-trial/blob/master/docs/rules/require-v-for-key.md

**Comment by bincute** [comment] 2019-01-17 04:13
You should add :key="x.id" of :key="other".  "It is recommended to provide a key with v-for whenever possible, unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains." form Vue documents.

**Comment by omid265** [comment] 2019-03-05 09:16
this work for me
<div :class="sliderClass()"  v-for="(slide,index) in slides" :key="index">

**Comment by gvargash** [comment] 2019-04-07 19:39
`<li v-for="categoria in arrayCategoria" :key="categoria.id">` ✅

**Comment by tvkit** [comment] 2019-04-11 06:01
> Just add the :key ...

If that wasn't obvious...

The following is not an uncommon usage of `v-for.`  How would the `vue/require-v-for-key` check be satisfied?

```
<table>
  <template v-for="row in rows">
    <tr><td>{{row.text}}</td></tr>
  </template>
</table>

```

**Comment by grugknuckle** [comment] 2019-04-11 11:50
> The following is not an uncommon usage of v-for. How would the vue/require-v-for-key check be satisfied?

@tvkit It's an easy modification of your code. Assuming that `rows` is an array, you can add this.

```
<table>
  <template v-for="(row, index) in rows" :key="index">
    <tr><td>{{row.text}}</td></tr>
  </template>
</table>
```

See my comment [above](https://github.com/vuejs/vetur/issues/261#issuecomment-371543211) about why this is really a problem with the vue.js documentation and NOT a problem with the vetur implementation of this rule.

**Comment by incompletude** [comment] 2019-05-09 21:55
I'm getting the error message when I don't need a key.

```
      <ul class="dropdown">
        <template v-for="(item, index) in items">
          <li v-bind:key="item.value">
            <a href>{{ item.text }}</a>
          </li>
          <template v-if="items[index + 1]">
            <li class="divider" v-if="item.group !== items[index + 1].group">a</li><!-- error -->
          </template>
        </template>
      </ul>
```

**Comment by paulcdejean** [comment] 2019-05-15 23:06
@grugknuckle this gives the error `- <template> cannot be keyed. Place the key on real elements instead.`

**Comment by Timmmm** [comment] 2019-12-20 14:46
I think this lint should be disabled. It clearly doesn't work properly.

* `:key` is **NOT** required in general. It is only required if your elements have state, so that Vue can keep track of them. If they are stateless (e.g. a simple `<li>`, `<a>` or `<p>`) then it is *NOT* required.
* You can work around it by using the index as a key: `v-for="(el, idx) in items" :key="idx"`. This is equivalent to not including a key at all and shouldn't be necessary.

This lint can be disabled until it can reliably detect that the elements contain state.

**Comment by sam-spain** [comment] 2020-01-09 12:55
I found this rule to not be helpful with the project I am working in and have disabled it. I am using VS Code and set up the ESLint extension. https://eslint.org/docs/user-guide/getting-started

In settings.json I disabled vetur's validation for templates with "vetur.validation.template": false"

And then in my rules for es lint (.eslintrc.js for me) I set "vue/require-v-for-key": "off"

I think this is less disruptive than changing each v-for when we are only iterating through data that will be static for the purpose of displaying. I haven't managed to get it to work with ignoring line below or entire file as they would be more preferable for some.

**Comment by jdspugh** [comment] 2020-01-24 04:40
Keys are used as hashes to optimise DOM rendering. If incorrectly used they will _slow performance and use more memory_ over automatically generated keys. People who don't understand what makes a good key will be generating poorer performance UIs than auto generated keys. That's why keys should be optional. Apart from the fact it's very annoying getting these errors and existing code shows errors.

**Comment by Timmmm** [comment] 2020-01-30 17:28
I've also tried adding this to my `.eslintrc.js` file's `rules` section, but it seems to be ignored by Vetur:

    "vue/require-v-for-key": "off",

**Comment by begueradj** [comment] 2020-02-27 06:11
As mentioned previously, we need to bind the `key` prop to a value. For example:
```
<div v-for="(item, index) in items">
  <!-- do stuff -->
 </div>
```
But is there a way to disable this rule ? There are multiple situations where it should be put off, for example when we work with slots.

**Comment by Silly-V** [comment] 2020-03-03 04:06
Is there some other extension which doesn't make these squiggly lines?

**Comment by bmaca** [comment] 2020-04-05 04:52
Just my simple solution down to this just in case runs into it later on. 
To the initial question `<li class="item-right" v-for="n in 19">{{ n }}</li>`

After Vue 2.2 this does not work in the latest Vue and throws an error. It needs have a `v-bind:key` directive

The fix is as simple as adding a key like this: `<li class="item-right" v-for="n in 19" :key="n">{{ n }}</li>`

**Comment by poonamrani** [comment] 2020-05-07 03:45
You should be using older version of VueJS but in latest versions key binding is mandatory to improve the performance of rendering the v-for elements. So please update your VueJS and check this.

To add v-bind:key you have to do something like this.

<li class="list-group-item" v-for="index in 5" v-bind:key="index">

Hope this answers your question.

**Comment by exse2** [comment] 2020-07-13 12:34
> in latest versions key binding is mandatory 

No. See https://vuejs.org/v2/api/#v-for

**Comment by calumk** [comment] 2021-01-26 10:01
+1 - Key does not seem to be mandatory, so why is an error forced here?

**Comment by yoyo930021** [comment] 2021-01-26 10:06
https://github.com/vuejs/vetur/issues/261#issuecomment-319755178

If you don't need this rule, you can disable `vetur.validation.template: false` and use ESLint for validate template.
