### ISSUE TITLE
[0.6.6]Multiple css/js suggest

### ISSUE THREAD

**Issue by Moerj** [octref/vetur#184] opened 2017-05-07 12:29 UTC
![qq20170507-202150 2x](https://cloud.githubusercontent.com/assets/13795438/25780921/78265b0e-3363-11e7-81eb-86b0c710759f.jpg)
![qq20170507-202205 2x](https://cloud.githubusercontent.com/assets/13795438/25780923/7ee54040-3363-11e7-9698-0c2dbee70cb0.jpg)
![qq20170507-202220 2x](https://cloud.githubusercontent.com/assets/13795438/25780924/82d54b3c-3363-11e7-99b3-197155f32da6.jpg)

When i write scss in the <style>.It show multiple suggest

**Comment by octref** [comment] 2017-05-07 13:12
Does this happen consistently?

![image](https://cloud.githubusercontent.com/assets/4033249/25781242/2e81fd4a-3305-11e7-943c-2be82bedc825.png)

Do you have a small project where I can repro the bug?

**Comment by Moerj** [comment] 2017-05-07 13:14
Occasional, sometimes normal

**Comment by octref** [comment] 2017-05-07 13:21
Let me know if you this happens to you again on a project that you can share with me.
I'll see what I can do. I can try to filter IntelliSense results, hopefully that wouldn't be too costly in terms of performance.

**Comment by cannap** [comment] 2017-05-07 13:27
i had the same as vetur was working on windows 10 :D

**Comment by octref** [comment] 2017-05-07 16:46
I'm guessing this happens when `jsLanguageService` is being recreated due to using a mix of TS and JS.
Are you guys working on a TS/JS mix project?

**Comment by Moerj** [comment] 2017-05-07 16:55
No. I only use *.js

**Comment by octref** [comment] 2017-05-07 16:57
[vetur-0.6.6.vsix.zip](https://github.com/octref/vetur/files/981760/vetur-0.6.6.vsix.zip)

@Moerj Can you try installing this version and see if that happens again?

**Comment by octref** [comment] 2017-05-08 01:19
NVM I found the bug.

**Comment by Moerj** [comment] 2017-05-10 01:59
![qq20170510-095200](https://cloud.githubusercontent.com/assets/13795438/25879895/bd519d60-3566-11e7-9c38-4b5f68e58412.jpg)

The 0.6.8 version js suggest also have this problem

**Comment by icehaunter** [comment] 2017-05-11 20:13
Yup, JS is repeating for me too. I think it happens every language server restart, but I am not sure

**Comment by octref** [comment] 2017-05-29 15:42
OK. The problem is each time the Language Service crashes and restarts itself, `onCompletion` will be bound again so the client will have two identical `CompletionProvider`.

Let me check with LSP people to see if this is the way it's supposed to work.

**Comment by octref** [comment] 2017-06-06 14:24
This is an upstream bug and will be resolved with LS@3.3.0 released later this week.

**Closed** 2017-06-19 20:34 UTC
Labels: bug, upstream
